spring:
  h2:
    console:
      enabled: true
  data:
    rest:
      basepath: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: 123
    initialization-mode: always
    initialize: true
    continue-on-error: true
    schema: "classpath:schema.sql"
    data: "classpath:data.sql"
    sqlScriptEncoding: UTF-8
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
management:
  endpoints:
    web:
      exposure:
        include: "info, health, logfile"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    defaults:
      enabled: true
logging:
  file: "homework16/src/main/resources/logfile.log"
