drop table if exists authors cascade;
drop table if exists books cascade;
drop table if exists comments cascade;
drop table if exists books_genre cascade;
drop table if exists genres cascade;
drop table if exists persons cascade;

drop table if exists acl_sid cascade;
drop table if exists acl_class cascade;
drop table if exists acl_entry cascade;
drop table if exists acl_object_identity cascade;

create table persons (id bigint generated by default as identity, username varchar(255) not null, password varchar(255) not null, role varchar(255) not null, primary key (id));
create table authors (id bigint generated by default as identity, author_name varchar(255) not null, primary key (id));
create table books (id bigint generated by default as identity, book_name varchar(255) not null, author_id bigint not null, primary key (id));
create table comments (id bigint generated by default as identity, comment varchar(255), book_id bigint not null, primary key (id));
create table genres (id bigint generated by default as identity, genre_name varchar(255) not null, primary key (id));
create table books_genre (book_id bigint not null, genre_id bigint not null, primary key(book_id,genre_id));
alter table books add constraint fk_book_author foreign key (author_id) references authors on delete cascade;
alter table books_genre add constraint fk_genre foreign key (genre_id) references genres;
alter table books_genre add constraint fk_book foreign key (book_id) references books on delete cascade;
alter table comments add constraint fk_comment_book foreign key (book_id) references books on delete cascade;


/*ACL Configuration*/
CREATE TABLE IF NOT EXISTS acl_sid (
  id smallserial,
  principal smallint NOT NULL,
  sid varchar(100) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_uk_1 UNIQUE(sid,principal)
);

CREATE TABLE IF NOT EXISTS acl_class (
  id smallserial,
  class varchar(255) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_uk_2 UNIQUE(class)
);

CREATE TABLE IF NOT EXISTS acl_entry (
  id smallserial,
  acl_object_identity bigint NOT NULL,
  ace_order int NOT NULL,
  sid bigint NOT NULL,
  mask int NOT NULL,
  granting smallint NOT NULL,
  audit_success smallint NOT NULL,
  audit_failure smallint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_uk_4 UNIQUE(acl_object_identity,ace_order)
);

CREATE TABLE IF NOT EXISTS acl_object_identity (
  id smallserial,
  object_id_class bigint NOT NULL,
  object_id_identity bigint NOT NULL,
  parent_object bigint DEFAULT NULL,
  owner_sid bigint DEFAULT NULL,
  entries_inheriting smallint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_uk_3 UNIQUE(object_id_class,object_id_identity)
);

ALTER TABLE acl_entry
ADD FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity(id);

ALTER TABLE acl_entry
ADD FOREIGN KEY (sid) REFERENCES acl_sid(id);

--
-- Constraints for table acl_object_identity
--
ALTER TABLE acl_object_identity
ADD FOREIGN KEY (parent_object) REFERENCES acl_object_identity (id);

ALTER TABLE acl_object_identity
ADD FOREIGN KEY (object_id_class) REFERENCES acl_class (id);

ALTER TABLE acl_object_identity
ADD FOREIGN KEY (owner_sid) REFERENCES acl_sid (id);