spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: 123
    initialization-mode: always
    initialize: true
    continue-on-error: true
    schema: "classpath:schema.sql"
    data: "classpath:data.sql"
    sqlScriptEncoding: UTF-8
  main:
    allow-bean-definition-overriding: true
  batch:
    initialize-schema: always
    job:
      enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #generate_statistics: true
        jdbc:
          batch_size: 66
          order_inserts: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: zubatacan@gmail.com
    password: AppleZ#3
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "logfile"
#        exclude: "health"
#      health:
#        show-details: always
logging:
  file: "backend/logfile.log"