drop table if exists batch_job_execution_context;
drop table if exists batch_job_execution_params;
drop table if exists batch_step_execution_context;
drop table if exists batch_step_execution;
drop table if exists batch_job_execution;
drop table if exists batch_job_instance;
drop sequence if exists batch_step_execution_seq;
drop sequence if exists batch_job_execution_seq;
drop sequence if exists batch_job_seq;


create table vines (
id bigint,
name varchar(255),
year bigint,
type varchar(255),
color varchar(255),
capacity decimal,
country varchar(255),
is_available boolean,
cost decimal,
producer_id bigint,
url varchar(255),
primary key (id));

create table producers (id bigint generated by default as identity, name varchar(255), primary key (id));
create table history (id bigint generated by default as identity, vine_id bigint, price decimal, date date, primary key (id));

create table persons (
id bigint generated by default as identity,
username varchar(255),
password varchar(255),
role varchar(255),
email varchar(255),
primary key (id));

create table favourite_vine (person_id bigint not null, vine_id bigint not null, primary key(person_id,vine_id));

alter table vines add constraint fk_vine_producer foreign key (producer_id) references producers on delete cascade;
alter table history add constraint fk_vine_history foreign key (vine_id) references vines on delete cascade;

alter table favourite_vine add constraint fk_vine foreign key (vine_id) references vines on delete cascade;
alter table favourite_vine add constraint fk_person foreign key (person_id) references persons on delete cascade;

