DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID INT PRIMARY KEY, AUTHORNAME VARCHAR(255));
CREATE TABLE BOOKS(ID INT PRIMARY KEY, BOOKNAME VARCHAR(255), AUTHORNAME VARCHAR(255));
CREATE TABLE GENRES(ID INT PRIMARY KEY, GENRENAME VARCHAR(255), BOOKNAME VARCHAR(255));