version: "3"
services:
  postgres:
    image: postgres
    ports: 
     - 5432:5432
    environment:
     - POSTGRES_USER=user
     - POSTGRES_PASSWORD=123
  server:
    image: server
    build: 
     context: .
     dockerfile: Dockerfile1
    ports:
     - 8081:8081
    environment:
     - spring.datasource.username=user
     - spring.datasource.password=123
     - spring.datasource.url=jdbc:postgresql://postgres/postgres
  client:
    image: client
    build: 
     context: .
     dockerfile: Dockerfile2
    ports:
     - 8080:8080
    environment:
     - rest.url=http://server
     - rest.port=8081
    depends_on:
     - "server"
    
