server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: 123
    initialization-mode: always
    initialize: true
    continue-on-error: true
    schema: "classpath:schema.sql"
    data: "classpath:data.sql"
    sqlScriptEncoding: UTF-8
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
logging:
  file: "homework18/src/main/resources/logfile.log"
